In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv('hiring.csv')

In [3]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
median_test = df['test_score(out of 10)'].median()

In [5]:
median_test

8.0

In [6]:
import math
median_test = math.floor(median_test)

In [7]:
median_test

8

In [8]:
df['test_score(out of 10)'].fillna(median_test, inplace=True)

In [9]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [10]:
df.experience.fillna("zero", inplace=True)

In [11]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [12]:
!pip install word2number

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5588 sha256=f8abbc896ef443befa663286d69a5ffc5a5a8944c81d7e8bc18f8ee3a8d28a79
  Stored in directory: c:\users\sujah\appdata\local\pip\cache\wheels\cd\ef\ae\073b491b14d25e2efafcffca9e16b2ee6d114ec5c643ba4f06
Successfully built word2number


In [13]:
from word2number import w2n

In [14]:
df.experience = df.experience.apply(w2n.word_to_num)

In [15]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [16]:
reg = linear_model.LinearRegression()

In [17]:
reg.fit(df[['experience','test_score(out of 10)', 'interview_score(out of 10)' ]], df['salary($)'])

LinearRegression()

In [18]:
reg.predict([[4, 7.5, 8.0]])

C:\Users\sujah\anaconda3\envs\MLBasics\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([60473.79912664])

In [22]:
reg.predict([[2,9,6]])

C:\Users\sujah\anaconda3\envs\MLBasics\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [23]:
reg.predict([[12,10,10]])


C:\Users\sujah\anaconda3\envs\MLBasics\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])